apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-gpu
  namespace: ml-training
  labels:
    app: model-training-gpu

spec:
  backoffLimit: 1

  template:
    metadata:
      labels:
        app: model-training-gpu

    spec:
      restartPolicy: Never

      containers:
        - name: train
          image: ghcr.io/rahul-ai-labs/mlops-train:latest
          imagePullPolicy: Always

          env:
            - name: CONFIG_PATH
              value: /app/configs/training_config.yaml
            - name: PYTHONPATH
              value: /app

          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"

            limits:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"

          volumeMounts:
            - name: training-config
              mountPath: /app/configs
              readOnly: true

            - name: training-data
              mountPath: /app/data

            - name: checkpoints
              mountPath: /app/checkpoints

      volumes:
        - name: training-config
          configMap:
            name: training-config

        - name: training-data
          persistentVolumeClaim:
            claimName: training-data-pvc

        - name: checkpoints
          persistentVolumeClaim:
            claimName: checkpoints-pvc