name: Start Containers

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to start"
        required: true
        type: choice
        options:
          - serve
          - train

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Start selected service
        env:
          SSHPASS: ${{ secrets.SSH_PWD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVICE: ${{ inputs.service }}
        run: |
          if [ "$SERVICE" = "serve" ]; then
            sshpass -e ssh \
              -o StrictHostKeyChecking=no \
              "${SSH_USERNAME}@${SSH_HOST}" \
              "cd /home/da25m609/mlops_pytorch_project && docker compose up -d serve"
          else
            sshpass -e ssh \
              -o StrictHostKeyChecking=no \
              "${SSH_USERNAME}@${SSH_HOST}" \
              "cd /home/da25m609/mlops_pytorch_project && docker compose --profile training run --rm -d train"
          fi